# Generated by Django 3.2 on 2024-10-25 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Название произведения, не более 256 символов', max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(help_text='Год выпуска, не больше текущего года', validators=[django.core.validators.MaxValueValidator(2024, message='Год должен быть не больше текущего.')], verbose_name='Год'),
        ),
    ]
